import jsPDF from 'jspdf'
import * as XLSX from 'xlsx'
import { dateTime } from '../utils/format'

export function exportPdf({ company, branch, account, title, columns, rows }) {
  const doc = new jsPDF()
  if (company.logo?.startsWith('data:image')) {
    try { doc.addImage(company.logo, 'PNG', 14, 12, 22, 22) } catch { /* optional company image */ }
  }
  doc.setFontSize(18)
  doc.text(company.name, 14, 22)
  doc.setFontSize(11)
  doc.setTextColor(90)
  doc.text(`${branch.name} | ${title}`, 14, 31)
  doc.text(`Generated by: ${account.fullName} | ${dateTime(new Date())}`, 14, 38)
  doc.setTextColor(30)
  let y = 51
  doc.setFont('helvetica', 'bold')
  doc.text(columns.join(' | '), 14, y)
  doc.setFont('helvetica', 'normal')
  rows.slice(0, 32).forEach((row) => {
    y += 7
    doc.text(row.map((value) => String(value).slice(0, 30)).join(' | '), 14, y)
  })
  doc.save(`${title.toLowerCase().replaceAll(' ', '-')}-${branch.code}.pdf`)
}

export function exportExcel({ title, rows, company, branch }) {
  const sheet = XLSX.utils.json_to_sheet(rows)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, sheet, title.slice(0, 31))
  XLSX.writeFile(workbook, `${title.toLowerCase().replaceAll(' ', '-')}-${company.name}-${branch.code}.xlsx`)
}
